### ISSUE TITLE
Evaluation Config for "vitl16_short.yaml"

### ISSUE THREAD

**Issue by lambert-x** [facebookresearch/dinov2#117]
Hi, I customized an evaluation config (shown below) for vit-large-16, however, the result is just 0.1% for Top-1 KNN accuracy. Could you please provide the evaluation config for the training config: [vitl16_short.yaml](dinov2/configs/train/vitl16_short.yaml)? 

My customized config:
```
student:
  arch: vit_large
  patch_size: 16
crops:
  global_crops_size: 224  # this is to set up the position embeddings properly
  local_crops_size: 96
```
