### ISSUE TITLE
[Question] Training setup on remote Ubuntu server

### ISSUE THREAD

**Issue by lxbanov** [facebookresearch/dinov2#497]
Hello! I am trying to setup a training of DinoV2 on custom unlabeled dataset on remote Ubuntu server. The server has 3 A100 available. However, when launching the training, the script spawns eight processes, each trying to occupy space on only one of GPUs. After few moments, the training fails due to insufficient GPU resources. I wish to reduce the number of processes and utilize all the available GPUs on the server. 

I tried changing `CUDA_VISIBLE_DEVICES` environment variable and tweak `train.batch_size_pre_gpu`, `num_workers` and `gpus_per_node` configuration parameters, but the behaviour of the script stays the same.

Here the configuration:

```yaml
# Training configuration for Dino V2 pretraining with a custom H5 dataset

train:
  # Here we tell the training pipeline to use our custom dataset
  # using the "H5Unlabeled" prefix followed by the absolute path.
  dataset_path: "H5Unlabeled:h5_filepath=data.h5"
  # Number of training epochs.
  epochs: 1000
  # Batch size per GPU (adjust depending on your GPU memory)
  batch_size_per_gpu: 2
  # Number of DataLoader workers.
  num_workers: 4
  gpus_per_node: 3

student:
  # Model architecture configurations (adjust based on your needs)
  arch: vit_giant2          # Options include vit_large, vit_base, etc.
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4

teacher:
  # Teacher network settings
  momentum_teacher: 0.994

optim:
  # Optimizer parameters.
  # The base_lr is set for batch size 1024, so adjust if necessary.
  base_lr: 2.0e-04
  weight_decay_end: 0.2
  warmup_epochs: 80
  layerwise_decay: 1.0

crops:
  local_crops_size: 98
  global_crops_size: 224
```

Could you please suggest how to control the number of processes spawned for the training and number (or IDs) of GPUs available?
